defaults:
  - _self_

ckpt_path: grappa-1.4.0
n_bootstrap: 1
store_test_data: false
test_data_path: null
accelerator: 'gpu'
plot: false

classical_force_fields: []

datasets: []
pure_test_datasets: null
ff_lookup: {}
splitpath: null

gradient_contributions: []
# - bond
# - angle
# - proper
# - improper
# - nonbonded
# - total

compare_forcefields: []

eval_model: true

grappa_contributions: null